<?php
// ----------------------------------------------------------------------
// Purpose: The purpose of this program is to plot the received values in the URL
// Description of the code 
//     Load the Google Charts library to create a line chart for visualizing the historical temperature data.
//     JavaScript code creates the chart using the temperature data stored in the session.
//     The chart displays the historical temperature.
//     The code plots the historical temperature data using a line chart generated by Google Charts.
// Author: Farid farahmand / 10/10/23
// Example: Assume the file name is message_plot.php
//     https://faridfarahmand.000webhostapp.com/message_plot.php?temp=30.5
// ----------------------------------------------------------------------



// Start or resume the session
session_start();

// Function to add a new temperature value to the historical data array
function addTemperatureValue($temp) {
    if (!isset($_SESSION['temperatures'])) {
        $_SESSION['temperatures'] = array();
    }
    array_push($_SESSION['temperatures'], $temp);
}

// Check if a temperature value is provided in the URL
if (isset($_GET['temp']) && is_numeric($_GET['temp'])) {
    $temperature = floatval($_GET['temp']);
    addTemperatureValue($temperature);
} else {
    $temperature = null;
}

// HTML for displaying the temperature values and chart
echo '<html>
<head>
    <title>Temperature Graph</title>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load("current", { packages: ["corechart"] });
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {
            var data = new google.visualization.DataTable();
            data.addColumn("string", "Time");
            data.addColumn("number", "Temperature (°C)");

            var temperatures = ' . json_encode($_SESSION['temperatures']) . ';

            for (var i = 0; i < temperatures.length; i++) {
                data.addRow([" " + (i + 1), temperatures[i]]);
            }

            var options = {
                title: "Temperature History",
                curveType: "function",
                legend: { position: "bottom" }
            };

            var chart = new google.visualization.LineChart(document.getElementById("chart_div"));
            chart.draw(data, options);
        }
    </script>
</head>
<body>
    <h1>Temperature Graph</h1>';

if ($temperature !== null) {
    echo '<p>Current Temperature: ' . $temperature . '°C</p>';
    echo '<h2>Historical Temperatures:</h2>';
    if (isset($_SESSION['temperatures'])) {
        echo '<div id="chart_div" style="width: 100%; height: 300px;"></div>';
        echo '<ul>';
        foreach ($_SESSION['temperatures'] as $tempValue) {
            echo '<li>' . $tempValue . '°C</li>';
        }
        echo '</ul>';
    }
} else {
    echo '<p>No valid temperature data provided in the URL.</p>';
}

echo '</body>
</html>';
?>
